<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b94b098e-a3a1-41d1-98ba-a371bfeff950</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="henglong.Web.Tests\**\*.cs" />
    <Content Remove="henglong.Web.Tests\**\*" />
    <None Remove="henglong.Web.Tests\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.14.0" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
  </ItemGroup>
</Project>
